#! /bin/bash
#
#  HOMEINFO Adobe AIR Application wrapper.
#
#  (C) 2017 HOMEINFO - Digitale Informationssysteme GmbH
#
#  Maintainer: Richard Neumann <r dot neumann at homeinfo period de>
#
####################################################################

APPLICATION_AIR="/usr/lib/application-air"
CMD="/opt/adobe-air-sdk/bin/adl -nodebug ${APPLICATION_AIR}/META-INF/AIR/application.xml ${APPLICATION_AIR}"
QUIET=false

while (( $# )); do
    case $1 in
        "--quiet")    QUIET=true
        ;;
    esac
    shift
done

if ${QUIET}; then
    exec ${CMD} 2> /dev/null
else
    exec ${CMD}
fi
