#! /bin/bash
#
#  kiosk - Disables screen blankening on the respective display.
#
#  This file is part of digital-signage.
#
#  digital-signage is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  digital-signage is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with digital-signage.  If not, see <http://www.gnu.org/licenses/>.
#
#  This unit provides a service to automatically login
#  the digital signage user to a certain terminal.
#
#  (C) 2015-2019: HOMEINFO - Digitale Informationssysteme GmbH
#
#  Maintainer: Richard Neumann <r dot neumann at homeinfo period de>
#
###############################################################################

XSET=/usr/bin/xset
GRACETIME=30


# Waits for X server to start.
wait_for_x() {
    local WAITED=0

    while ! ${XSET} q &> /dev/null; do
        if [ ${WAITED} -lt ${GRACETIME} ]; then
            sleep 1
        else
            echo "X server did not come up after ${WAITED} seconds."
            return 10
        fi

        (( WAITED++ ))
    done

    echo "X server took ${WAITED} seconds to start up."
    return 0
}


# Disables screen blankening.
disable_screen_blankening() {
    if ! ${XSET} s 0 0 &> /dev/null; then
        echo "Could not disable screen blankening (s 0 0)."
        return 1
    fi

    if ! ${XSET} s noblank &> /dev/null; then
        echo "Could not disable screen blankening (s noblank)."
        return 2
    fi

    if ! ${XSET} s off &> /dev/null; then
        echo "Could not disable screen blankening (s off)."
        return 3
    fi

    if ! ${XSET} dpms 0 0 0 &> /dev/null; then
        echo "Could not disable DPMS (dpms 0 0 0)."
        return 4
    fi

    if ! ${XSET} -dpms &> /dev/null; then
        echo "Could not disable DPMS (-dpms)."
        return 5
    fi

    echo "Successfully disabled screen blankening on ${DISPLAY}."
    return 0
}


wait_for_x && disable_screen_blankening