#! /bin/bash

XSET=/usr/bin/xset
GRACETIME=30
XSERVERRC=/etc/xserverrc


# Waits for X server to start.
wait_for_x() {
    local WAITED=0

    while ! ${XSET} q &> /dev/null; do
        if [ ${WAITED} -lt ${GRACETIME} ]; then
            sleep 1
        else
            echo "X server did not come up after ${WAITED} seconds."
            return 10
        fi

        (( WAITED++ ))
    done

    echo "X server took ${WAITED} seconds to start up."
    return 0
}


disable_screen_blankening() {
    if ! ${XSET} s 0 0 &> /dev/null; then
        echo "Could not disable screen blankening (s 0 0)."
        return 1
    fi

    if ! ${XSET} s noblank &> /dev/null; then
        echo "Could not disable screen blankening (s noblank)."
        return 2
    fi

    if ! ${XSET} s off &> /dev/null; then
        echo "Could not disable screen blankening (s off)."
        return 3
    fi

    if ! ${XSET} dpms 0 0 0 &> /dev/null; then
        echo "Could not disable DPMS (dpms 0 0 0)."
        return 4
    fi

    if ! ${XSET} -dpms &> /dev/null; then
        echo "Could not disable DPMS (-dpms)."
        return 5
    fi

    echo "Successfully disabled screen blankening on ${DISPLAY}."
    return 0
}


wait_for_x && disable_screen_blankening

if [ -f "${XSERVERRC}" ]; then
    echo "Invoking ${XSERVERRC}."
    # shellcheck disable=SC1090
    source "${XSERVERRC}"
else
    echo "Warning: ${XSERVERRC} is missing." >&2
fi
