#! /bin/bash
#
#  migrate-digsig - Migrate digital signage data.
#
#  This file is part of digital-signage.
#
#  digital-signage is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  digital-signage is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with digital-signage.  If not, see <http://www.gnu.org/licenses/>.
#
#  This unit provides a service to automatically login
#  the digital signage user to a certain terminal.
#
#  (C) 2020: HOMEINFO - Digitale Informationssysteme GmbH
#
#  Maintainer: Richard Neumann <r dot neumann at homeinfo period de>
#
###############################################################################


OLD_DIR="/usr/share/digsig"
NEW_DIR="/var/lib/digsig"


if [ -L "${OLD_DIR}" ] && [ -d "${NEW_DIR}" ]; then
	exit 0	# Already migrated.
fi

if [ ! -d "${NEW_DIR}" ]; then
	mkdir "${NEW_DIR}"
	chown digsig.digsig "${NEW_DIR}"
fi

if [ -d "${OLD_DIR}" ]; then
	cp -auv "${OLD_DIR}"/* "${NEW_DIR}"/
	rm -rf "${OLD_DIR}"
fi

if [ ! -e "${OLD_DIR}" ]; then
	ln -s "${NEW_DIR}" "${OLD_DIR}"
fi
