#! /bin/bash

OLD_DIR="/usr/share/digsig"
NEW_DIR="/var/lib/digsig"


if [ -L "${OLD_DIR}" ]; then
	exit 0	# Already migrated.
fi

if [ -d "${OLD_DIR}" ]; then
	cp -auv "${OLD_DIR}"/* "${NEW_DIR}"/
	rm -rf "${OLD_DIR}"
fi

if [ ! -e "${OLD_DIR}" ]; then
	ln -s "${NEW_DIR}" "${OLD_DIR}"
fi
