#! /bin/bash

# Put any kiosk mode customization here.
#
# XXX: Note that the X server might need a few seconds to start
#      up before you can invoke any X server related commands.
#      If this script fails, so will the start of the xorg-server.service.

true
